{{- if .Values.jupyter.enabled -}}
{{- $secretName := print (include "dragon.secretName" .) "-jupyter-token" -}}
{{- $previous := lookup "v1" "Secret" .Release.Namespace $secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  annotations:
    # Keep the Secret when uninstalling the chart.
    "helm.sh/resource-policy": keep
type: Opaque
data:
  jupyter_token: {{ if $previous }}{{ index $previous.data "jupyter_token" }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
{{- end }}