{{- if .Values.frontend.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "dragon.fullname" . }}-frontend
  labels:
    {{- include "dragon.frontendLabels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dragon.fullname" . }}-frontend
  labels:
    {{- include "dragon.frontendLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "dragon.fullname" . }}-frontend
subjects:
  - kind: ServiceAccount
    name: {{ include "dragon.frontendServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
