apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "dragon.frontendAppLabel" . }}
  # name: {{ include "dragon.fullname" . }}-frontend
  {{- with .Values.frontend.jobAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "dragon.frontendLabels" . | nindent 4 }}
    {{- with .Values.frontend.jobLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ttlSecondsAfterFinished: {{ .Values.frontend.ttlSecondsAfterFinished }}
  completions: 1
  parallelism: 1
  backoffLimit: 0
  template:
    metadata:
      {{- with .Values.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dragon.frontendLabels" . | nindent 8 }}
        {{- with .Values.frontend.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: Never
      {{- with .Values.frontend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dragon.frontendServiceAccountName" . }}
      {{- with .Values.frontend.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          {{- with .Values.frontend.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: FRONTEND_JOB_LABEL
              value: {{ include "dragon.frontendAppLabel" . | quote }}
            {{- with .Values.frontend.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.frontend.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: {{ .Values.sharedMemoryVolume.name }}
              mountPath: {{ .Values.sharedMemoryVolume.mountPath }}
            - name: backend-job
              mountPath: /config
            {{- with .Values.frontend.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: {{ .Values.sharedMemoryVolume.name }}
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.sharedMemoryVolume.sizeLimit }}
        - name: backend-job
          configMap:
            name: {{ include "dragon.fullname" . }}-backend
        {{- with .Values.frontend.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end}}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
